# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            page_title
tagline:          'page_Tag_line'
description:      'page_description'
url:              http://pedromzadeh.github.io
baseurl:          /

author:
  name:           'Pedrom Zadeh'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
