# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            site_title
tagline:          'site_Tag_line'
description:      'site_description'
url:              http://pedromzadeh.github.io
baseurl:          /

author:
  name:           'Pedrom Zadeh'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
